### ISSUE TITLE
大域探索の規格化について

### ISSUE THREAD

**Issue by hamcchi** [issp-center-dev/2DMAT#13]
質問がございます。早稲田大学高山研究室 修士２年の濱田雅史と申します。
現在東大物性研のスーパーコンピューターohtaka上でpy2dmatを用いた大域探索を考えています。

大域探索を行うにあたり、規格化を'TOTAL'ではなく、'MAX'で行いたいと考えています。
このような設定をするには、どうすればよいでしょうか。
お答えいただけると幸いです。
よろしくい願い致します。

**Comment by k-yoshimi** [comment]
https://issp-center-dev.github.io/2DMAT/manual/master/ja/solver/sim-trhepd-rheed.html
にあるのですが、postセクションのnormalizationをMAXにすることで実施できます。
よろしくお願いします。

**Comment by hamcchi** [comment]
ohtaka内の以下のパスにあるファイルの中身をいじくるということでしょうか。
/home/issp/materiapps/intel/python3/python3-3.8.6-1/lib/python3.8/site-packages/py2dmat/solversim-trhepd-rheed.py

またスパコン上ではpython3のパッケージソフトは共用で皆さんが使われるファイルという認識なのですが、自分用にいじくってもよいのでしょうか。

**Comment by k-yoshimi** [comment]
いえ、入力ファイルで設定できます。

**Comment by k-yoshimi** [comment]
具体的には以下のようなものを入力ファイルにいれていただけると設定可能です。
入力ファイルは
```
[base]
dimension = 3

[solver]
name = "sim-trhepd-rheed"

[solver.config]
calculated_first_line = 5
calculated_last_line = 74
row_number = 2

[solver.param]
string_list = ["value_01", "value_02", "value_03" ]
degree_max = 7.0

[solver.reference]
path = "experiment.txt"
first = 1
last = 70

[algorithm]
name = "minsearch"
label_list = ["z1", "z2", "z3"]

[algorithm.param]
min_list = [0.0, 0.0, 0.0]
max_list = [10.0, 10.0, 10.0]
initial_list = [5.25, 4.25, 3.50]
```
のようになっていますが、ここに

```
[solver. post]
normalization = "MAX"
```
という風に書いていただけると設定できます。

**Comment by hamcchi** [comment]
入力例の記載ありがとうございます。
使い方の理解が深まりました。

また不明な点がありましたらご連絡いたします。
よろしくお願いいたします。

**Comment by k-yoshimi** [comment]
はい、こちらこそよろしくお願いします。
