### ISSUE TITLE
東大物性スパコンのexeファイルについて

### ISSUE THREAD

**Issue by hamcchi** [issp-center-dev/2DMAT#15]
いつもお世話になっております、早稲田大学 高山研究室の濱田雅史と申します。

東大物性研スパコンないにあるexeファイルについてお伺いしたい点があります。

スパコン上で2DMATの大域探索を行ったのですが、各grid点における計算結果(surf-bulkP.s)がgithubに上がっているsrcフォルダから作成したbulk.exe、surf.exeによる計算結果と大きく異なっていました。

参考に、あるgrid点におけるbulk.txtとsurf.txtのテキストファイル、またこれらをスパコン、自前PCで計算（github上のsrcフォルダから作成したexeファイルにより計算）し比較したものをエクセルファイルとして添付いたします。

ここで質問なのですが、スパコン内の以下のpath内にあるbulk.exe、surf.exeが2DMATの大域探索で、実行されていると思うのですが、これらは何か新しく更新されたものなのでしょうか。

「/home/issp/materiapps/intel/sim_trhepd_rheed/sim_trhepd_rheed-prerelease_0/bin/」

ご確認いただけると幸いです。
よろしきお願い致します。 

[スパコン_自前PC_比較.xlsx](https://github.com/issp-center-dev/2DMAT/files/6432428/_.PC_.xlsx)
[bulk.txt](https://github.com/issp-center-dev/2DMAT/files/6432440/bulk.txt)
[surf.txt](https://github.com/issp-center-dev/2DMAT/files/6432441/surf.txt)

**Comment by k-yoshimi** [comment]
@hamcchi 
ご指摘ありがとうございます。自前のPCとohtakaで直接gitからcloneしてコンパイル・計算したものを比較すると、同じ結果を返すのですが、確かにohtakaにプリインストールされているものを使用すると異なる結果を返すことを確認しました。担当者に確認してみますので、少々お待ちいただければと思います。よろしくお願いします。

**Comment by k-yoshimi** [comment]
ちなみに、自前でコンパイルしたbulk.exeの結果をもとに、プリインストールされたsurf.exeを実行すると正しい結果を返すので、bulk.exeがおかしいようです。

**Comment by hamcchi** [comment]
早急な対応、誠にありがとうございます。
よろしくお願い致します。

**Comment by k-yoshimi** [comment]
@hamcchi 
bulk.exeの差し替えを取り急ぎ行いましたので、ご確認をよろしくお願いします。
sim_trhepd_rheed側でテストツールを導入するよう提案するなど、再発防止をするようにしようと思いますが、またおかしな点がありましたら、ご連絡ください。

**Comment by hamcchi** [comment]
ご対応ありがとうございます。
今大域探索を改めて実行したところ、計算は正常でした。
これからも何卒よろしくお願い致します。
