### ISSUE TITLE
Mapperでのmesh_pathを用いた計算

### ISSUE THREAD

**Issue by k-yoshimi** [issp-center-dev/2DMAT#57]
mesh_pathを使用する際、パラメータの組み合わせが一つだけだとエラーで落ちる。
> File "2DMAT/src/py2dmat/algorithm/_algorithm.py", line 263, in _meshgrid
    return grid[id_list, :], id_list
IndexError: too many indices for array

また、マニュアルにあるメッシュ定義ファイルの説明の箇所で、「2列目以降は [solver.param] セクションにある、 string_list で定義された変数に入る値が入ります。」とあるが、string_listがない場合にどのような挙動になるのかが分からない(string_listがない場合には関係ない？)。
https://issp-center-dev.github.io/2DMAT/manual/master/ja/algorithm/mapper_mpi.html

**Comment by yomichi** [comment]
2列目以降がそのまま $f(\vec{x})$ の $\vec{x}$ になります。 `string_list` については、 `sim-trhepd-rheed` solver しかなかった頃の名残ですね。直します。

**Comment by yomichi** [comment]
Fixed in #58.
